Restructuration du reset
levydanqc/stockaccino pull request #11
Opened 2022-03-19 16:56 UTC by OlivierPoitras

Le reset du mot de passe est maintenant divisé par ses fonctions.

2022-03-19 17:46 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.html
> +<div *ngIf="editor == 'confirm'">
@OlivierPoitras Il faut que tu fasses plus attention au code que tu copies-colle.. tu ne l'adaptes presque pas à la situation ou tu ne le clean pas après

2022-03-19 17:47 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.html
> +<div *ngIf="editor == 'confirm'">
Exemple: là tu utilise un statement pour confirmer quel est la valeur de `editor`

2022-03-19 17:48 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +  }
Et là, tu définis des méthodes de validation du contenu de la variable, ce qui est exactement pareil

2022-03-19 17:49 UTC, levydanqc requested changes

2022-03-19 17:49 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +  }
C'est mieux d'utiliser ces méthodes là plutôt que de valider à chaque fois dans le html
Imagines que tu viens à changer les values dans editor, alors tu dois retrouver le code dans le html alors qu'avec ça: tu n'as qu'un seul endroit où le changer

2022-03-19 17:53 UTC, levydanqc requested changes

2022-03-19 17:53 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +  switchForm(type: EditorType) {
Tu n'appelles jamais cette méthode.

2022-03-19 17:54 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +  switchForm(type: EditorType) {
C'est un duplicate de la méthode dans authentification.component.ts

2022-03-19 17:57 UTC, levydanqc requested changes

2022-03-19 17:57 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.html
> +    <p>DEBUG (temporaire): Code: {{this.code}}</p>
Finalement c'est parfait comme ça, on va garder le fait d'afficher le code pour qu'on puisse le tester

2022-03-19 23:33 UTC, OlivierPoitras commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +  switchForm(type: EditorType) {
Bien vu, je l'ai supprimée.

2022-03-19 23:35 UTC, OlivierPoitras commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +  }
C'est réglé, bien vu

2022-03-19 23:35 UTC, OlivierPoitras commented on front-end/src/app/authentication/components/reset/reset.component.html
> +<div *ngIf="editor == 'confirm'">
c'est réglé, j'ai utilisé les fonctions get a la place

2022-03-19 23:37 UTC, OlivierPoitras commented on front-end/src/app/authentication/components/reset/reset.component.html
> +    <p>DEBUG (temporaire): Code: {{this.code}}</p>
Good, et j'ai supprimé l'affichage inutile du email.

2022-03-20 15:03 UTC, levydanqc requested changes

2022-03-20 15:03 UTC, levydanqc commented on front-end/src/app/service/user.service.ts
>      return this.http.get<any>(url, {
@OlivierPoitras Check if this is valid: 
```suggestion
    return this.http.get<User>(url, {
```

2022-03-20 16:52 UTC, levydanqc requested changes

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/authentication/authentication.component.html
> +<!-- <a href="" style="position: absolute; top: 0; left: 0; margin: 20px; cursor: pointer;"><button
@OlivierPoitras Si on a pas besoin de ce commentaire, il faut le remove

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/authentication/components/login/login.component.html
> +    <button (click)="submit()" fxFill mat-raised-button color="primary">Se connecter</button>
@OlivierPoitras Partout où il y a le symbol d'interdit en bas de fichier dans github c'est qu'il manque une ligne vide finale

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +export type EditorType = 'request' | 'confirm' | 'reset';
@OlivierPoitras  Si tu as besoin de mettre ces commentaires pour mieux expliquer les variables, c'est qu'elles sont mal nommés
Change les pour qu'elles soient plus explicite (il faut favoriser un nom plus long mais plus compréhensible)

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +    this.emailRequested = 'temporaire@debug.com';
@OlivierPoitras Avons-nous vraiment besoin de l'email si c'est juste pour le debug

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +  reset() {
T'as PR s'appelle 'restructuration du reset', mais il te manque ce code

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/authentication/components/signin/signin.component.html
> +    <button (click)="this.submit('signin')" type="submit" fxFill mat-raised-button color="primary">S'inscrire</button>
@OlivierPoitras Le event de submit n'est plus nécessaire puisqu'il n'est pas utilisé

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/home/components/dashboard/dashboard.component.html
> +        <!-- <a href="/account"><button class="btn btn-dark btnPerso">Login (temporaire, test button)</button></a> -->
@OlivierPoitras  Pareil ici, il reste des commentaires à retiré

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/home/components/dashboard/dashboard.component.ts
> +  ngOnInit(): void {}
@OlivierPoitras si le OnInit n'est pas nécessaire alors il faut le retirer

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/service/user.service.ts
> +  // Verifie si le email et le mot de passe sont corrects pour l'utilisateur
@OlivierPoitras Pareil ici, si le commentaire est nécessaire, c'est que c'est mal nommé

2022-03-20 16:52 UTC, levydanqc commented on front-end/src/app/userPost.ts
> +export interface IUserPost {
@OlivierPoitras Je suis pas mal sur qu'on peut trouver une façon de ne pas avoir cette interface

2022-03-20 17:25 UTC, OlivierPoitras commented on front-end/src/app/authentication/authentication.component.html
> +<!-- <a href="" style="position: absolute; top: 0; left: 0; margin: 20px; cursor: pointer;"><button
c'est fait

2022-03-20 17:27 UTC, OlivierPoitras commented on front-end/src/app/authentication/components/login/login.component.html
> +    <button (click)="submit()" fxFill mat-raised-button color="primary">Se connecter</button>
c'est deja a submit() et non a onSubmit(), je ne vois pas le bug, et ok pour les lignes finales

2022-03-20 17:28 UTC, OlivierPoitras commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +    this.emailRequested = 'temporaire@debug.com';
on le garde, comme ca le code est deja ecrit au moment ou on voudrait envoyer le email

2022-03-20 17:30 UTC, OlivierPoitras commented on front-end/src/app/authentication/components/reset/reset.component.ts
> +  reset() {
on ne reset pas encore le mot de passe comme on avait dit, c'est normal, donc on garde la fonction, comme ca au moment de reset le mot de passe lorsqu'on aura géré le email et code, on peut remplir la fonction reset

2022-03-20 17:31 UTC, OlivierPoitras commented on front-end/src/app/home/components/dashboard/dashboard.component.html
> +        <!-- <a href="/account"><button class="btn btn-dark btnPerso">Login (temporaire, test button)</button></a> -->
good c'est fait

2022-03-20 17:32 UTC, OlivierPoitras commented on front-end/src/app/home/components/dashboard/dashboard.component.ts
> +  ngOnInit(): void {}
c'est pas moi qui l'ai fait, mais je viens de le retirer, bien vu

2022-03-20 17:35 UTC, OlivierPoitras commented on front-end/src/app/service/user.service.ts
> +  // Verifie si le email et le mot de passe sont corrects pour l'utilisateur
meme etant bien nommé, ca ne fait pas de mal d'avoir ce commentaire pour décrire la fonction, alors je vais le laisser pour l'instant, puisque je travaille encore beaucoup avec le user service, donc c'est utile d'avoir directement le commentaire pour differencier les fonctions en travaillant sur celles-ci. Lorsque le user service sera terminé, je retirerai les commentaires

2022-03-20 17:46 UTC, merged