Modification du compte
levydanqc/stockaccino pull request #18
Opened 2022-03-20 21:44 UTC by OlivierPoitras

2022-03-20 21:57 UTC, levydanqc requested changes

2022-03-20 21:57 UTC, levydanqc commented on front-end/src/app/home/components/settings/settings.component.ts
> +    console.log("1");
Ce n'est plus nécéssaire

2022-03-20 21:57 UTC, levydanqc commented on front-end/src/app/home/components/settings/settings.component.ts
> +    }
@OlivierPoitras Il ne faut pas utiliser les getElementById mais plutôt set des variables à utiliser dans le code, comme on fait partout ailleurs

2022-03-20 21:57 UTC, levydanqc commented on front-end/src/app/home/components/settings/settings.component.ts
> +
@OlivierPoitras  même principe, tu n'utilises jamais ces méthodes...

2022-03-20 21:57 UTC, levydanqc commented on front-end/src/app/home/components/settings/settings.component.ts
> +
Please fait plus attention au code

2022-03-20 21:57 UTC, levydanqc commented on front-end/src/app/service/user.service.ts
> +      console.log("5");
@OlivierPoitras retires tout tes console.log avant de merge

2022-03-20 22:03 UTC, OlivierPoitras commented on front-end/src/app/home/components/settings/settings.component.ts
> +
oui je les utilise plusieurs fois

2022-03-20 22:04 UTC, OlivierPoitras commented on front-end/src/app/home/components/settings/settings.component.ts
> +    console.log("1");
ca va etre retiré au prochain push

2022-03-20 22:04 UTC, OlivierPoitras commented on front-end/src/app/service/user.service.ts
> +      console.log("5");
ca va etre retiré au prochain push

2022-03-20 22:07 UTC, OlivierPoitras commented on front-end/src/app/home/components/settings/settings.component.ts
> +    }
Pour l'instant ,je n'ai pas reussi a utiliser les variables, mais  meme si les getElementById ne sont pas la meilleure solution, ca fonctionne pour l'instant. Ca sera un improvement a faire. Crois moi, j'ai beaucoup essayé à utiliser les formControls

2022-03-20 22:46 UTC, levydanqc commented on front-end/src/app/home/components/settings/settings.component.ts
> +    }
@OlivierPoitras Base toi sur les autres fichiers, dans login et signin, j'utilise les forms control, c'est juste un attribut à appliquer au input
Notre code devrait être constant dans la manière dont il est écrit et utiliser le dom en angular n'est pas la meilleur manière...
Corrige le pour le sprint 1 please, c'est vraiment très simple

2022-03-20 22:49 UTC, levydanqc requested changes

2022-03-20 22:49 UTC, levydanqc commented on front-end/src/app/home/components/settings/settings.component.ts
> +
@OlivierPoitras tu les utilises à quelques endroits true, mais tu utilises encore `*ngIf="currentMode == 'show'"` et tu ne devrais pas puisque c'est te répéter

2022-03-20 22:50 UTC, levydanqc commented
@OlivierPoitras Lorsque tu termines ton code, demande moi en review et lorsque tu as fait des changements, il faut que tu appuis sur le reload button dans la section review pour me redemander

2022-03-22 15:19 UTC, levydanqc approved these changes

2022-03-22 15:20 UTC, merged