Add trending suggestion
levydanqc/stockaccino pull request #56
Opened 2022-04-12 22:55 UTC by levydanqc

2022-04-17 03:33 UTC, OlivierPoitras requested changes

2022-04-17 03:33 UTC, OlivierPoitras commented on back-end/Services/YahooService.cs
> -        {"trending", "v1/finance/trending/CA"},
On veut pas plutot CA?

2022-04-17 03:33 UTC, OlivierPoitras commented on front-end/src/app/home/components/recommendation/components/suggestion/suggestion.component.scss
> +    background-color: #e0e0e0;
faudrait mettre une constante

2022-04-17 03:33 UTC, OlivierPoitras commented on front-end/src/app/home/components/recommendation/components/trending/trending.component.ts
> +    this.yahooService.getTrending().subscribe((data: Trending[]) => {
console log inutile ici

2022-04-17 03:33 UTC, OlivierPoitras commented on front-end/src/app/home/components/recommendation/recommendation.component.scss
> +}
a moins qu'elles soit uniques, il faudrait mettre des constantes pour les couleurs ici

2022-04-17 03:33 UTC, OlivierPoitras commented on front-end/src/app/home/components/sidenav/sidenav.component.scss
>  }
c'est minime mais oublie pas de changer px a rem

2022-04-17 03:33 UTC, OlivierPoitras commented on front-end/src/assets/constants.ts
>    static readonly USER_URL: string = this.BASE_URL + 'users/';
assure toi que c'etait voulu de push les URL switched et commented

2022-04-19 00:29 UTC, levydanqc commented on back-end/Services/YahooService.cs
> -        {"trending", "v1/finance/trending/CA"},
Non j'utilise plus trending... je vais le delete

2022-04-19 00:31 UTC, levydanqc commented on front-end/src/app/home/components/recommendation/recommendation.component.scss
> +}
C'est du unique, on ne les réutilise jamais

2022-04-19 00:32 UTC, levydanqc commented on front-end/src/app/home/components/recommendation/components/suggestion/suggestion.component.scss
> +    background-color: #e0e0e0;
Same here, c'est unique juste pour imiter un hover, on veux pas polluer nos constantes si on le réutilise pas

2022-04-19 00:33 UTC, levydanqc commented on front-end/src/assets/constants.ts
>    static readonly USER_URL: string = this.BASE_URL + 'users/';
Whooops!!!

2022-04-21 22:56 UTC, levydanqc commented on front-end/src/app/home/components/sidenav/sidenav.component.scss
>  }
C'est voulu, c'est pour le style du bouton trending

2022-04-21 22:57 UTC, levydanqc commented on front-end/src/app/home/components/recommendation/components/trending/trending.component.ts
> +    this.yahooService.getTrending().subscribe((data: Trending[]) => {
Cleaned

2022-04-22 00:26 UTC, OlivierPoitras approved these changes

2022-04-22 14:55 UTC, merged